### PR TITLE
Update qc_mentorship.md

### PR DESCRIPTION
**Pull request by tlubowe**
Adding a Privacy Policy to the mentorship page. 

I might be inclined to throw this on the bottom of the entire website but will defer to others for thoughts there.

### CODE REVIEW

**Comment by mstechly** [comment]
Looks good to me :)

**Comment by tbabej** [comment]
Two general comments:
* Instead of linking to a Google Doc, maybe we should make this a static Markdown page within the repo?
* This looks like a general template, but some portions might not apply to us. For example, I don't think `qosf.org` sets any cookies :slightly_smiling_face:

**Comment by tlubowe** [comment]
Good to know we dont set cookies! Will remove this (definitely a template lol). 

Taking a pass at a separate page now

**Comment by markf94** [comment]
I'm very much in favour of merging the other MR that applies the privacy policy to the whole page!

**Comment by tlubowe** [comment]
> I'm very much in favour of merging the other MR that applies the privacy policy to the whole page!

Im pretty sure this now just has a link to that other MR - so that other one is a full page but the link to find it lives on this page at the bottom. That was the original intent at least. It might be nice to have this live as a link on the bottom of every page for qosf.org though. Will defer to you all for thoughts on that

**Comment by mstechly** [comment]
Let's close @markf94 ?

**Comment by markf94** [comment]
Closing since we merged !48

**Pull request closed without merging**
