### PR TITLE
Mentorship page updates

### PR DESCRIPTION
**Pull request by lzylili**
Hi! 

**Changes as follows:**
- Copy updates to the current page for the mentorship program 
- Created a subpage for the cohort 1 project showcase

**What is still missing:** 
- Application link 
- Contact link (at the bottom of the main mentorship program page)

@mstechly if you could help fill these in, that'd be great!

### CODE REVIEW

**Comment by lzylili** [comment]
Hi @markf94 @tbabej! 

We updated the mentorship page and moved the project showcase to a subpage (`cohort_1.md`). 

The only thing left that needs to be fixed is the internal page links on `qc_mentorship.md` to `cohort_1.md` - I couldn't figure out how to link it properly so I left the URLS as LINK_COHORT_1.

If you could help fix this link issue and then merge this branch, that'd be great (so the website will be out in time once applications are released for the mentorship program). Thanks!

**Comment by lzylili** [comment]
Hi @markf94 @tbabej!

The link has been fixed - please help merge to the main branch so that the website can be deployed before the application is released. Thanks so much!

**Comment by tbabej** [comment]
Looks good to me, I will deploy ASAP.

**Comment by tbabej** [comment]
Changes are live.

**Pull request merged**
